### ISSUE TITLE
Sharing other characters' current Spirit status

### ISSUE THREAD

**Issue by jbblily** [ksx0330/FVTT-Kamigakari-System#1]
Thank you for developing Kamigakari system.
My teammates made a feedback that he wants to see through all the other players' Spirit pool at a glance (etc. dice pool on the map or on the separate window) 
I think it would be useful for some kamigakari pcs who can support party members' Spirit dice costs.
It would shorten time taken by opening others' character sheets and check their current spirit dice.

카미가카리 시스템을 개발해주셔서 감사합니다. 
저희 팀원끼리 세션을 하던 중 나온 피드백 중 하나입니다만, 영력 보조 서포터들은 다른 사람들의 영력 상황을 주시하는 것이 필요한데 일일히 다른 사람들의 시트를 켜면서 확인하기 번거로운 부분이 있습니다. 
별도의 창이나 맵 위에서 현재 플레이어들의 영력 상황을 확인할 수 있었으면 합니다. 
여건이 되고 가능하다면 요청드리고 싶습니다. 감사합니다.

**Comment by ksx0330** [comment]
Updated in 0.4.0. You can see "Spirit Dice Viewer" in scene controls
