### ISSUE TITLE
Bug : Start and end talent list doesn't appear

### ISSUE THREAD

**Issue by jbblily** [ksx0330/FVTT-Kamigakari-System#12]
Thank you for your cool idea!
I like your updated version, but it's kinda buggy... 
Start and end talent list is not shown properly.
Can you check it one more time?

Also, I think older version of your system breaks after the updates... so I had to make a new world to apply it.

Nice idea, but I think there are too much automations in combat tracker. If it's possible, can you make an option to turn it on or off? (I like your macros, though) 

업데이트 감사합니다. 적용 후 확인해보았는데, 조금 버그가 있는 것 같습니다.
개시와 종료 시 탤런트 창이 뜨지 않습니다.  한번 다시 체크해주실 수 있나요?

또, 기존에 만들어 두었던 월드는 업데이트 후에 오류가 나는 것 같습니다... 이니셔티브를 굴려도 key 가 존재하지 않는다는 오류가 뜹니다 
새 월드를 만들어야 적용이 되더군요. 그냥 참고해주시면 감사하겠습니다.

전투 자동화는 좋은 아이디어지만, 너무 자동화가 많이 되어있다보니 오류도 많고 약간 번거롭다는 생각이 듭니다. 
또, 하우스룰이나 특수 기믹 등에 유연하게 적용하기 어렵지 않나 싶습니다. 
혹시 괜찮다면, 전투 관련 대화창을 띄우는 기능을 옵션으로 만들어서 키고 끌 수 있도록 해주실 수 있나요? 
(타이밍 별로 사용 가능한 탤런트 띄워주는 매크로는 좋은 것 같습니다.) 

![image](https://user-images.githubusercontent.com/18694887/122724972-78a32680-d2af-11eb-96ff-d85952c8aafd.png)

**Comment by ksx0330** [comment]
Thank you for using this system.
First, about the opening and ending talent.
For current GM, no dialogs will appear for each timing (like start and end).
This was intended, but if there is a better opinion, I will reflect it.

Secondly, the problem related to the initiative was solved in version 1.0.2.
Please let me know if there are any problems after the update.

In the case of combat automation, we added that it is a beginner-friendly element.
I will add an option that can be removed for skilled people.

You told me that the talent macro part is convenient, but we have updated the Token Action Hood module. We have put PR in Token Action Hud, and if the update is completed, it will be more convenient to use.

이 시스템을 사용해주셔서 감사합니다.
먼저, 개시와 종료 탤런트에 대해서입니다. 
현재 GM인 경우에는 각 타이밍 별 행동(개시 및 종료)을 요구하는다이얼로그가 나타나지 않습니다.
이건 의도한 부분이었습니다만, 더 좋은 의견이 있다면 반영하도록 하였습니다.

두 번째로 이니셔티브 관련된 문제는 1.0.2 버전에서 해결했습니다.
업데이트 이후에도 문제가 생긴다면 알려주시길 바랍니다.

전투 자동화의 경우에는 초보자 친화적인 요소라 추가를 하였지만,
숙련자분들을 위해 제거할 수 있는 옵션을 추가하도록 하겠습니다.

탤런트 매크로 부분이 편리하다고 이야기 주셨는데, 이번에 Token Action Hud 모듈에 대응한 업데이트를 진행했습니다. Token Action Hud 측에 PR를 넣은 상태이고, 업데이트가 완료된다면 더 편리하게 이용할 수 있게 되겠네요.

**Comment by ksx0330** [comment]
Dialogue setting and Start, End bugs were fixed in version 1.0.3.

**Comment by jbblily** [comment]
Found out that I can solve this problem by deleting old version's [battle] actor and restart combat. (Also found out that Combat carousel module breaks this system... this module is deprecated so no problem.)
Thank you for your help.

**Comment by ksx0330** [comment]
Combat carousel is now working
Update new version
