### ISSUE TITLE
Bug : Influence bug

### ISSUE THREAD

**Issue by jbblily** [ksx0330/FVTT-Kamigakari-System#17]
After the dice roll, when I try Influence, it refreshes the world. 
Please check this out. Thank you.

다이스 굴림 후 채팅의 영력 조작 버튼으로 영력조작을 시행한 후 확인을 누르면 월드가 새로고침되며 영력조작한 결과가 반영되지 않습니다.

**Comment by ksx0330** [comment]
Fixed
