### ISSUE TITLE
Update code for consistency

### ISSUE THREAD

**Issue by NotoriusNeo** [ksx0330/FVTT-Kamigakari-System#19]
With #18 merged with master, the item names should be updated too.

![image](https://user-images.githubusercontent.com/89462237/130653892-95fea343-a507-438b-ac1e-e0d83c555d69.png)

Race -> Ancestry
Style -> Facet

I tried doing this on my end, which made all my created items disappear. I think this is because they aren't registering for the new names. This might need some macros to update the existing item names to the new ones.

So, I humbly request your help!

Appreciated!

**Comment by ksx0330** [comment]
Fixed
