### ISSUE TITLE
Categorizing Talents

### ISSUE THREAD

**Issue by jbblily** [ksx0330/FVTT-Kamigakari-System#2]
Thank you for updating and maintaining Kamigakari System.
I would like to ask you some minor improvements. 

**1. Actors' Talent alignment**
Instead of splitting talents depending on their categories (e.g. Race, Common, etc), I would like to align them depending on level.
This makes clear on which level I acquired that talent, and also makes it feel similar to official character sheet of Kamigakari.
Kamagakari allows exchanging one talent when Pc's level goes up, but only the talents of same level limitations.
So I think aligning talents by level is needed for rebuilding characters.

**2. Categorizing Talents**
There are ◎ ○ marks on some talents, which mean they have level or style limitation to be used.
I would like to mark it in front of both Enemy and Actors' talents.
Especially, high-level boss enemy adds more spirit heals depending on the number of marked talents.
Categories like Race, Common, etc can be shown separately, for example, as tags. 

I appreciate your hard work. 

카미가카리 시스템 유지 보수에 항상 수고가 많으십니다. 
약간의 개선을 요청드리고 싶습니다.

**1. 액터의 탤런트 정렬**
현재 공통 탤런트, 종족 탤런트 등으로 나누어 접어서 표현하게 되어있으나, 탤런트 종류보다는 '탤런트 습득 레벨' 에 따라 정렬할 수 있었으면 합니다.
카미가카리의 룰 상, 세계 간섭 레벨이 1 오를 때마다 탤런트 하나를 교체할 수 있는데 반드시 해당 탤런트의 세계 간섭 레벨 제한과 동일해야 합니다. (5레벨이 되었다고 해서 1레벨때 습득한 탤런트를 5레벨 탤런트로 교체하는 것이 불가능)
그러므로, 해당 탤런트가 어느 레벨 대에 습득한 것인지 알기 쉽게 정렬할 수 있었으면 좋겠다고 생각합니다.
또 이렇게 하는 편이 공식 캐릭터 시트와 비슷한 느낌을 주기 좋을 것이라고 생각합니다.

**2. 탤런트 분류**
1에서 탤런트 정렬을 레벨 순으로 바꾸는 대신, 탤런트에 태그 등을 매겨 분류할 수 있도록 하면 좋지 않을까 합니다.
탤런트 목록을 자세히 보면 ◎ ○마크들이 있는데 이것은 레벨이나 칭호 제한이 있는 탤런트들입니다.
또, 고위 보스 에너미들은 고위 보스 탤런트들이 있으며, 이 역시 몇가지 마크가 붙어있는데 세션 종료 후 영문 회복량에 영향을 미칩니다. 
이런 것들을 보기 쉽게 하기 위해 카테고리화하면 좋지 않을까 합니다. 

저희 팀이 고위 레벨 세션을 많이 하는 탓에, 몇가지 편의성 개선을 요청합니다.
항상 감사드립니다.

**Comment by ksx0330** [comment]
Adding the level part of the talent seems to be a necessary feature.  In addition, classification by level can be sufficiently implemented.

 However, I don't understand how the talent categorization part is needed.  The basic talent has a talent separator such as ◎ ○, and when using it, I did not feel the need for additional tags.  Please explain in detail what parts need to be added.

탤런트의 레벨 부분 추가는 필요한 기능인 것 같습니다. 또한 레벨 별 분류도 충분히 구현 가능한 부분입니다.

다만, 탤런트의 카테고리화 부분이 어떻게 필요한지 이해가 되지 않습니다. 기본 탤런트에는 ◎ ○ 등의 탤런트 구분자가 있고 사용 시에 별 다른 추가 태그의 필요성을 느끼지 못했습니다. 어떤 부분의 추가가 필요한지 자세히 설명을 부탁 드립니다.

**Comment by jbblily** [comment]
Thank you for your kind answer. 
It was just my suggestion, so if you don't feel any necessity for it, I think it is ok to stay on this way.
Just to make my question clear, what I meant was that, I just wanted to make sure some points I can miss (talent categories, or calculations of experience points and spirit points at the end of the session). 
I don't feel any problem without it so, I think you can ignore #2. Thank you again!

답변 감사드립니다.
카테고리화 부분은 작성 당시에 '이러면 편하지 않을까?' 싶어 적어둔 부분인데, 필요성이 느껴지지 않는다면 세션에 별 지장이 없는 부분으로 이대로도 충분하다고 생각합니다.
다만 제 실수를 교정하기 위해 질문을 좀더 깔끔하게 다듬어 명확하게 다시 써두자면, 고위 보스 탤런트 중 세션 종료 후 추가로 영문을 회복시키는 것들이나, 그밖에 못 보고 놓쳐 실수 하기 좋은 것들을 실수 하지 않기 위해 몇가지 특성(종족이라던가, 마크들이라던가) 태그를 붙여두면 좋지 않을까 했던 것입니다.
다시 생각해보니 이러한 것들 없이도 아무런 문제가 없기 때문에, 2번은 무시해주셔도 좋을 것 같습니다. 다시한번 감사드립니다!
