### ISSUE TITLE
Visibility of enemy sheets

### ISSUE THREAD

**Issue by jbblily** [ksx0330/FVTT-Kamigakari-System#20]
Thank you for your hard works. 
Is it possible to limit the information of enemy sheets according to the permissions of players?
For example, if player1's permission is 'Limited', it only shows basic informations and no other stats.
This would be usefull when controlling boss, since it can only show basic informations even when players successs to view the information.

항상 감사합니다. 
혹시 에너미 시트 공개 권한에 따라 표시되는 정보가 달라지도록 할 수 있을까요? 
예를 들어, 시트 권한이 플레이어 1에게 'Limited'로 설정되어 있으면 기본 정보( 종별, 약점 등) 만 보이도록 하는 것처럼요.
탐지 판정이 성공해도 보스는 기본 정보만 공개되기 때문에, Limited 권한으로 시트의 일부만 공개하는 것이 편리할 것 같습니다.

**Comment by ksx0330** [comment]
Updated
