### ISSUE TITLE
Some Enhancements

### ISSUE THREAD

**Issue by jbblily** [ksx0330/FVTT-Kamigakari-System#21]
I want to request some enhancements.

 1. Bigger Spirit Dice viewer actor select box
 
![image](https://user-images.githubusercontent.com/18694887/149495310-f8efd324-43b2-46a6-bedb-b9ad766538cd.png)
I want the size as big as this picture...

 2. HP/Spirit Reset
 
![image](https://user-images.githubusercontent.com/18694887/149495448-13e6f931-964b-4f78-ab58-a576b4bd59de.png)
I want to reset my characters' HP and Spirit after the end of the session, in a handy way.

Can you add a feature to reset HP and Spirit, by clicking "headers" of them? 

Thank you for your nice work.

---

몇가지 간단한 기능 요청이 있어서 이슈 남깁니다. 

(pr을 넣고 싶었지만, 능력이 안되서 아쉽습니다 :( )

1. 영력 다이스 뷰어 액터 선택창 확장
액터가 많을 때 창이 좁아서 좀 거슬렸습니다. 크게 보고 싶습니다. 본 스샷과 비슷한 정도로 크게는 어려울까요? (height 480px)
혹은 모퉁이를 끌어서 확대/축소가 가능해도 좋습니다...! 

2. HP/영력 리셋
세션이 끝난 뒤 간편하게 리셋하고 싶습니다. 시트에서 HP와 영력 헤더를 누르면 HP는 최대치까지, 영력은 22까지 자동으로 리셋되도록 해주실 수 있을까요? 

항상 멋진 작업 감사합니다.

**Comment by ksx0330** [comment]
It has been updated in version 0.4.6.
