### ISSUE TITLE
Can't roll initiative on combat tracker

### ISSUE THREAD

**Issue by jbblily** [ksx0330/FVTT-Kamigakari-System#22]
Hi, thank you for your nice work.

I updated this system few days ago, and I realized that I can't roll initiative on combat tracker after the update.

Can you fix this issue?

안녕하세요, 항상 잘 쓰고 있습니다. 

며칠 전에 시스템 업데이트를 했습니다. 그런데 컴뱃 트래커에서 캐릭터의 행동치가 굴러가지 않는 문제를 발견했습니다. 

혹시 수정해주실 수 있을까요?

**Comment by ksx0330** [comment]
It has been updated in version 0.4.8
