### ISSUE TITLE
Is there a way to add additional spirit dice?

### ISSUE THREAD

**Issue by Zalmute** [ksx0330/FVTT-Kamigakari-System#26]
There is a way to gain up to two additional spirit dice in this game. How do I gain extra dice?

**Comment by ksx0330** [comment]
Use Set Spirit Dice Pull macro among the macros in the compendium.

**Comment by Zalmute** [comment]
There is a typo in the set spirit dice pool command.  but otherwise, that helped - thank you!
![Spirit Macro 3](https://user-images.githubusercontent.com/94233136/213903075-abb92d6c-4ac4-4393-bdfb-b06a433b376c.png)

**Comment by ksx0330** [comment]
Fixed
