### ISSUE TITLE
Bug on Dice template 

### ISSUE THREAD

**Issue by jbblily** [ksx0330/FVTT-Kamigakari-System#28]
![image](https://user-images.githubusercontent.com/18694887/214308712-cfe3093d-0262-44a3-8d8f-2b5ce23dd441.png)
![image](https://user-images.githubusercontent.com/18694887/214309433-37207240-2710-4328-9bd7-f12f6f9b670f.png)

굴림 수식: /roll 2d6 # 2~ 5:없음, 6~ 9: 무도복, 10~ : 검은띠

공식 아티클에 적혀있는 대로 /roll 다이스 수식 # 텍스트 이렇게 적었는데 첫번째 주사위 이미지가 엉뚱한데 들어가네요... 

https://foundryvtt.com/article/dice/

**Comment by ksx0330** [comment]
Fixed
