### ISSUE TITLE
Compatibility Issue (0.7.5 ver.)

### ISSUE THREAD

**Issue by jbblily** [ksx0330/FVTT-Kamigakari-System#3]
There are some compatibility problems on core ver. 0.7.5

**1. No spirit dice change button on rolls**
![캡처](https://user-images.githubusercontent.com/18694887/97199799-c4bacb80-17f3-11eb-9317-e14f7ea5e7bd.PNG)

**2. Spirit changes are not reflected to sheets, or spirit value resets, after Spirit Burn**

These are all I found after the update. 

0.7.5 버전 업데이트 후 호환성 문제가 있습니다.
1. 판정 후 영력 교환 버튼이 보이지 않는 문제
2. 영문 소비 후 영문이 리셋되거나 영문 소모가 반영되지 않는 문제

아직까지는 이 두가지 문제가 제가 발견한 호환성 문제 전부입니다.

**Comment by ksx0330** [comment]
Updated in 0.4.2. update core to 0.7.6
