### ISSUE TITLE
영력 주사위 현황 권한 문제

### ISSUE THREAD

**Issue by jbblily** [ksx0330/FVTT-Kamigakari-System#30]
안녕하세요, 멋진 시스템 감사합니다.

다름이 아니라 영력 주사위 현황 (왼쪽 바에서 음양 아이콘 누르면 나오는거) 에 나타나는 캐릭터 권한을 조정해주셨으면 합니다.

소유자가 아니라 '관찰자' 권한이라도 영력 주사위 현황에 띄울 수있게 해주실 수 있을까요?

모든 PC 토큰을 서로가 서로의 소유자로 넘겨주었더니 플레이어들이 실수로 남의 캐릭터 토큰을 눌러서 발화하다가 캐릭터가 섞입니다... 

소유하지 않은 캐릭터를 관찰자 권한으로 두고 싶은데, 그러면 영력 현황을 서로 공유할 수 없게 됩니다.

이점에서 개선이 가능할까요? 감사합니다...

**Comment by ksx0330** [comment]
1.5.4 버전에서 영력 주사위 현황에서 "관찰자" 권한도 볼 수 있도록 수정했습니다.
Observer / Owner 버튼을 클릭하면 "관찰자, 소유자 / 소유자" 권한의 액터를 볼 수 있습니다.

<img width="304" alt="image" src="https://github.com/ksx0330/FVTT-Kamigakari-System/assets/15700174/a4406736-9c11-47cb-b46d-7a1201bbb4ae">

<img width="302" alt="image" src="https://github.com/ksx0330/FVTT-Kamigakari-System/assets/15700174/b26e1b1f-fafd-486a-8a4f-79dab2773bf1">
