### ISSUE TITLE
데미지 적용 권한 문제

### ISSUE THREAD

**Issue by CloudFlavorKettle** [ksx0330/FVTT-Kamigakari-System#31]
<img width="1036" alt="chrome_tgHNRJ2rX3" src="https://github.com/ksx0330/FVTT-Kamigakari-System/assets/75537760/b10318cb-681a-4bd3-b308-a7e04901baef">

안녕하세요. 카미가카리 모듈을 사용하는 도중 테스트를 하다가 데미지 적용이 되지 않는 현상이 발생했습니다.
이미지에 나온 것은 플레이어로 접속 했을 때 적용이 되지 않은 것이고, 게임 마스터로 접속했을 때만 적용됩니다.

개발자 도구에 나온 오류는 다음과 같습니다.

foundry.js:59187 User Player2 lacks permission to update Actor [hQdjZ4NM4HD7mCnE]
fetch @ foundry.js:59187
damage.js:273 Uncaught (in promise) Error: User Player2 lacks permission to update Actor [hQdjZ4NM4HD7mCnE]
    at ServerDatabaseBackend._updateDocuments (/foundryvtt/resources/app/dist/database/backend/server-backend.mjs:1:3830)
    at async Semaphore._try (/foundryvtt/resources/app/common/utils/semaphore.mjs:101:17)

해당 적 캐릭터의 소유권을 가진 채로 적용하는 것은 가능했지만 플레이어가 적 캐릭터의 소유권을 가질 경우 시나리오에 대한 스포일러가 있을 수 있어 혹여 수정해주실 수 있는지 여쭙고 싶습니다. 늘 고생하십니다. 감사합니다.

**Comment by ksx0330** [comment]
에너미에게 대미지 적용을 하기 전에 에너미 시트에서 대미지 감소 처리를 해줘야 합니다.
그렇기에 마스터가 모든 세팅을 마치고 대미지 적용 버튼을 누르는 것을 추천합니다.

캐릭터가 다른 캐릭터에 대해서 회복 처리를 할 경우를 제외하고는 플레이어가 대미지 적용을 할 일은 없다고 생각하면 좋겠습니다.

**Comment by CloudFlavorKettle** [comment]
확인 했습니다. 감사합니다.
