### ISSUE TITLE
Translastions are all over the place

### ISSUE THREAD

**Issue by souldymono** [ksx0330/FVTT-Kamigakari-System#8]
I know this isn't an actual issue but it's kind of irritating that you use terms from the fan translation and officail translation interchangeably, can you please use one or the other? The system is great otherwise but this is proving confusing for my players sometimes since we use the fan translation. It's especially confusing for me when I look at an npc's damage reduce tab and see Armor and Barrier when the sheet says Guard and Ward.

**Comment by ksx0330** [comment]
Thank you for using this system.
All armor and barrier are changed to guard, ward.
Please update this system
