### ISSUE TITLE
replace window.prompt 

### ISSUE THREAD

**Issue by BrotherSharper** [ksx0330/FVTT-Kamigakari-System#9]
Hello!

I am bringing this message from a user of the Japanese FVTT community. I am merely translating this so please let me know if there's anything you need clarification of.

------
Using Spirit Burn's Transcended and Spirit Dies I get the following error on console when clicking them:
```
electron/js2c/renderer_init.js:167 Uncaught (in promise) Error: prompt() is and will not be supported.
    at window.prompt (electron/js2c/renderer_init.js:167)
    at KamigakariActorSheet._transcend (actor-sheet.js:403)
    at HTMLButtonElement.dispatch (jquery.min.js:2)
    at HTMLButtonElement.v.handle (jquery.min.js:2)
window.prompt @ electron/js2c/renderer_init.js:167
_transcend @ actor-sheet.js:403
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
```

My setup is as follows:
- Windows10
- FoundryVTT 0.7.9
- FVTT-Kamigakari-System 0.8.0

I believe the reason for this is the lack of window.prompt() support in the native app of Foundry VTT. I'd appreciate it if you could replace this with alternative UI such as Dialog.

**Comment by ksx0330** [comment]
Update in 0.8.2
